characters/urls.py
from django.urls import path

from characters.views import CharacterListView, MyCharacterListView, add_character, CreateCharacterView, \
    SubjectsListView, give_up_character, CharacterDeleteView

urlpatterns = [
    path('characters/', CharacterListView.as_view(), name='characters'),
    path('my_characters/', MyCharacterListView.as_view(), name='my_characters'),
    path('take_character/<int:character_id>', add_character, name='take'),
    path('give_up_character/<int:character_id>', give_up_character, name='give_up'),
    path('new_character/', CreateCharacterView.as_view(), name='new'),
    path('school/', SubjectsListView.as_view(), name='school'),
    path('delete/<int:pk>', CharacterDeleteView.as_view(), name='delete'),
]

chat/urls.py
from django.urls import path

from chat.views import NewMessageView, MyMessagesListView

urlpatterns = [
    path('new/', NewMessageView.as_view(), name='new'),
    path('messages/', MyMessagesListView.as_view(), name='messages')
]

forum/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView
from rest_framework_swagger.views import get_swagger_view

from forum.views import ForumListView, ForumPageView, AllSectionsView, SystemPostFormView, like, dislike, \
    GamePostFormView, PostDeleteView, SingleSectionView

schema_view = get_swagger_view(title='Sections API Documentation')

urlpatterns = [
    # app urls
    path('list/', ForumListView.as_view(), name='list'),
    path('page/<int:pk>', ForumPageView.as_view(), name='page'),
    path('new/system/', SystemPostFormView.as_view(), name='new_system'),
    path('like/<int:pk>', like, name='like'),
    path('dislike/<int:pk>', dislike, name='dislike'),
    path('new/game/', GamePostFormView.as_view(), name='new_game'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='delete'),

    # api urls
    path('api/sections/', AllSectionsView.as_view(), name='api_sections'),
    path('api/sections/<int:pk>/', SingleSectionView.as_view(), name='api_section'),
    url(r'^documentation/', schema_view, name='doc'),
]

friends/urls.py
from django.urls import path, re_path

from friends.views import FriendsListView, subscribe, unsubscribe

urlpatterns = [
    path('friends/', FriendsListView.as_view(), name='friends_list'),
    re_path('subscribe/(?P<pk>\d+)', subscribe, name='subscribe'),
    path('unsubscribe/<int:pk>', unsubscribe, name='unsubscribe'),
]

role_game_forum/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path

from role_game_forum import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    url('', include('foundation.urls')),
    re_path(r'^characters/', include(('characters.urls', 'characters'), namespace='Characters')),
    re_path(r'^forum/', include(('forum.urls', 'forum'), namespace='Forum')),
    re_path(r'^friends/', include(('friends.urls', 'friends'), namespace='Friends')),
    re_path(r'^chat/', include(('chat.urls', 'chat'), namespace='Chat')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="{% static 'jquery/jquery-3.4.1.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}"/>
    <title>Школа волшебства Уагаду</title>
    <link rel="shortcut icon" href="{% static 'images/icon.png' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery/docs.min.js' %}"></script>
</head>
<style>
    .header {
        background-image: url({% static 'images/banner2.jpg'%});
        box-shadow: 0 0 10px rgb(74, 48, 54);
        text-shadow: black 0 0 4px;
        height: 220pt;
    }
</style>
<body>
<header>
    <script>
        /* When the user clicks on the button,
        toggle between hiding and showing the dropdown content */
        function myFunction() {
            document.getElementById("myDropdown1").classList.toggle("show");
        }

        // Close the dropdown if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }

        function myFunction2() {
            document.getElementById("myDropdown2").classList.toggle("show");
        }

        // Close the dropdown if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }

        function myFunction3() {
            document.getElementById("myDropdown3").classList.toggle("show");
        }

        // Close the dropdown if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }


    </script>
    <div class="header">
        <h1 align="right" class="header-text1">
            Школа волшебства
        </h1>
        <h1 align="right" class="header-text2">
            <a href="{% url 'main_page' %}"> Уагаду</a>
        </h1>
    </div>

    <div>
        <ul id="main-menu" class="nav nav-tabs" align="center">
            <li class="nav-item dropdown">
                {% if user.is_authenticated %}
                    <a class="nav-link dropdown-toggle" href="#" onclick="myFunction(); return false"
                       role="button">Профиль</a>
                    <div class="dropdown-menu" id="myDropdown1">
                        <a class="dropdown-item" href="{% url 'profile' pk=request.user.id %}">Мой профиль</a>
                        <a class="dropdown-item" href="{% url 'Friends:friends_list' %}">Мои друзья</a>
                        <a class="dropdown-item" href="{% url 'Chat:messages' %}">Мои сообщения</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
                    </div>
                {% else %}
                    <a class="nav-link dropdown-toggle" href="#" onclick="myFunction(); return false"
                       role="button">Вход</a>
                    <div class="dropdown-menu" id="myDropdown1">
                        <a class="dropdown-item" href="{% url 'login' %}">Войти</a>
                        <a class="dropdown-item" href="{% url 'registration' %}">Регистрация</a>
                    </div>
                {% endif %}
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" onclick="myFunction2(); return false"
                   role="button">Персонажи</a>
                <div class="dropdown-menu" id="myDropdown2">
                    <a class="dropdown-item" href="{% url 'Characters:characters' %}">Список персонажей</a>
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'Characters:new' %}">Создание персонажа</a>
                        <a class="dropdown-item" href="{% url 'Characters:my_characters' %}">Мои персонажи</a>
                    {% endif %}
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" onclick="myFunction3(); return false"
                   role="button">Игра</a>
                <div class="dropdown-menu" id="myDropdown3">
                    <a class="dropdown-item" href="{% url 'plot' %}">Сюжет</a>
                    <a class="dropdown-item" href="{% url 'navigation' %}">Навигация</a>
                    <a class="dropdown-item" href="{% url 'Characters:school' %}">О школе</a>
                    <a class="dropdown-item" href="{% url 'rules' %}">Правила</a>
                    <a class="dropdown-item" href="{% url 'Forum:list' %}">Обсуждения</a>
                    {% if user.is_authenticated %}
                        {% if user.is_admin %}
                            <a class="dropdown-item" href="{% url 'Forum:api_sections' %}">API раздел</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'Forum:doc' %}">Документация API</a>
                    {% endif %}
                </div>
            </li>
            <li>
                <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'search' %}">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="search" placeholder="Поиск пользователей"
                           aria-label="Search"
                           id="search" name="q">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
                </form>
            </li>
        </ul>
    </div>
</header>

<div>
    {% block content %}
    {% endblock %}
</div>

<div>
    <p></p>
</div>
<footer class="page-footer font-small pt-4">
    <div class="footer-copyright text-center py-3">© 2020 Copyright: Cherbaeva Daria</a>
    </div>
</footer>

</body>
</html>