chat/urls.py
from django.urls import path

from chat.views import NewMessageView, MyMessagesListView

urlpatterns = [
    path('new/', NewMessageView.as_view(), name='new'),
    path('messages/', MyMessagesListView.as_view(), name='messages')
]

foundation/urls.py
from django.urls import path, re_path
from foundation.views import MainPageView as Main, registration_view as registration, ProfileView, ProfileEditView, \
    PlotView, NavigationView, RulesView, SearchResultView

urlpatterns = [
    path('register/', registration, name='registration'),
    path('', Main.as_view(), name='main_page'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/edit', ProfileEditView.as_view(), name='profile_edit'),
    path('plot/', PlotView.as_view(), name='plot'),
    path('navigation/', NavigationView.as_view(), name='navigation'),
    path('rules/', RulesView.as_view(), name='rules'),
    path('search/', SearchResultView.as_view(), name='search'),
]

friends/urls.py
from django.urls import path, re_path

from friends.views import FriendsListView, subscribe, unsubscribe

urlpatterns = [
    path('friends/', FriendsListView.as_view(), name='friends_list'),
    re_path('subscribe/(?P<pk>\d+)', subscribe, name='subscribe'),
    path('unsubscribe/<int:pk>', unsubscribe, name='unsubscribe'),
]

role_game_forum/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path

from role_game_forum import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    url('', include('foundation.urls')),
    re_path(r'^characters/', include(('characters.urls', 'characters'), namespace='Characters')),
    re_path(r'^forum/', include(('forum.urls', 'forum'), namespace='Forum')),
    re_path(r'^friends/', include(('friends.urls', 'friends'), namespace='Friends')),
    re_path(r'^chat/', include(('chat.urls', 'chat'), namespace='Chat')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

foundation/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import User
from django.db import models


class SiteUserManager(BaseUserManager):
    def create_user(self, username, email=None, password=None):
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password, email=None, ):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save(using=self._db)
        return user


class SiteUser(AbstractBaseUser):
    username = models.CharField(max_length=40, unique=True)
    email = models.EmailField(max_length=60, blank=True)
    is_admin = models.BooleanField(default=False)
    status = models.CharField(max_length=100, blank=True)
    photo = models.ImageField(blank=True, upload_to='photos')
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'username'

    objects = SiteUserManager()

    def __str__(self):
        return self.username

    # For checking permissions. to keep it simple all admin have ALL permissions
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    @staticmethod
    def has_module_perms(app_label):
        return True

foundation/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from foundation.models import SiteUser


class SiteRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=60)
    photo = forms.ImageField

    class Meta:
        model = SiteUser
        fields = ('username', 'email', 'password1', 'password2')

foundation/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from django.views.generic import TemplateView, DetailView, UpdateView, ListView

from forum.models import Post
from foundation.forms import SiteRegistrationForm
from foundation.models import SiteUser
from friends.models import Subscription


def registration_view(request):
    context = {}
    if request.POST:
        form = SiteRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            # email = form.cleaned_data.get('email')
            # raw_password = form.cleaned_data.get('password1')
            # account = authenticate(email=email, password=raw_password)
            # login(request, account)
            return redirect('login')
        else:
            context['registration_form'] = form
    else:
        form = SiteRegistrationForm()
        context['registration_form'] = form
    return render(request, 'registration/register.html', context)


class MainPageView(TemplateView):
    template_name = 'foundation/main_page.html'


class ProfileView(DetailView):
    model = SiteUser
    template_name = 'foundation/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts_counter'] = Post.objects.filter(author_id=self.object.id).count()
        if self.object != self.request.user:
            if Subscription.objects.filter(subscriber_id=self.request.user.id, subscriptor_id=self.object.id).exists():
                context['is_sub'] = True
            else:
                context['is_sub'] = False

        return context


class ProfileEditView(LoginRequiredMixin, UpdateView):
    template_name = 'foundation/profile_edit.html'
    model = SiteUser
    fields = ('email', 'username', 'status', 'photo')
    success_url = reverse_lazy('main_page')


class PlotView(TemplateView):
    template_name = 'foundation/plot.html'


class NavigationView(TemplateView):
    template_name = 'foundation/navigation.html'


class RulesView(TemplateView):
    template_name = 'foundation/rules.html'


class SearchResultView(ListView):
    model = SiteUser
    template_name = 'foundation/search_result.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = SiteUser.objects.filter(
            Q(username__icontains=query) | Q(email__icontains=query)
        )
        return object_list

templates/foundation/about_school.html
{% extends 'base.html' %}

{% block content %}
    <div class="page-title" align="center">
        <h3>Общая информация</h3>
    </div>
    <div class="main-page-text">
        <p>Подготовительный языковой год для студентов, не знающих суахили – 9 лет.</p>
        <p>Первый год обучения – 10 лет. Общие обязательные предметы, такие как история магии, полёты на мётлах, основы
            волшебства и другие, знакомство с возможными факультетами, экзамены и распределение по факультетам в конце
            года.
        </p>
        <p>Средний этап обучения, обязательный – с 11 до 18 лет. Изучаются как профильные предметы каждого факультета,
            так
            и обязательные дисциплины. В конце восьмого года обучения студентами сдаются экзамены, и выдаётся аттестат
            об
            окончании школы, после которого можно продолжить обучение в специализированных школах в Африке или
            заграницей
            или же начинать работать там, где не требуется сертификат о прохождении заключительного этапа обучения в
            Уагаду.
        </p>
        <p> Заключительный этап обучения, по желанию – с 18 до 21 года. Обычно ученики, остающиеся на этот этап, в
            будущем
            занимаются наукой, поступают на службу в Объединённое Министерство Магии Африки или его отделения в родных
            странах или же остаются преподавать в школе. На последнем году обучения студенты сдают выпускные экзамены и,
            в
            случае удачной сдачи, могут получить работу на лучших условиях, чем их однокурсники, провалившие эти
            испытания.
        </p>

    </div>
    <div class="page-title" align="center">
        <h3>Список предметов</h3>
    </div>

    <div class="main-page-text">
        {% if subjects %}
            {% for s in subjects %}
                <div class="main-page-text">Название: {{ s.name }}</div>
                {% if s.teacher %}
                    <div class="main-page-text">Учитель: {{ s.teacher.name }} {{ s.teacher.last_name }}</div>
                {% else %}
                    <div class="main-page-text">Учитель: нет.</div>
                {% endif %}
            {% endfor %}
        {% else %}
            Ни одного предмета не создано.
        {% endif %}
    </div>

    <div class="page-title" align="center">
        <h3>Список факультетов</h3>
    </div>

    <div class="main-page-text">
        {% if faculties %}
            {% for f in faculties %}
                <div class="main-page-text"><b>{{ f.name }}</b></div>
                <img class="avatar" width="200" height="180" align="center" src="{{ f.animal.url }}"/>
                <div class="main-page-text">{{ f.description }}</div>
            {% endfor %}
        {% else %}
            Ни одного факультета не создано.
        {% endif %}
    </div>
{% endblock %}

templates/foundation/main_page.html
{% extends 'base.html' %}

{% block content %}

    <div class="page-title" align="center">
        <h3>Добро пожаловать!</h3>
    </div>

{% endblock %}

templates/foundation/navigation.html
{% extends 'base.html' %}

{% block content %}

    <div class="page-title" align="center">
        <h3>Волшебные существа</h3>

    </div>
    <div class="main-page-text">
        <p><b>Громамонт (англ. Erumpent)</b>, в других переводах взрывопотам или сносорог — это крупное серое
        африканское
        животное, весом до тонны, обладающее огромной силой. На большом расстоянии громамонта можно перепутать с
        носорогом. Он имеет толстую шкуру, которая отражает большинство заклятий и проклятий, острый рог на носу и
        длинный хвост, похожий на верёвку. У громамонтов обычно рождается один детёныш. Громамонт нападает, только если
        его раздразнить, и последствия этого, как правило, весьма плачевны. Рог громамонта протыкает всё что угодно, от
        кожи до металла, и содержит вещество, которое, проникнув в тело жертвы, взрывается. Популяция громамонтов
        невелика, так как самцы часто взрывают друг друга во время брачного периода. Африканские волшебники обращаются с
        громамонтами очень осторожно. Рога, хвосты и взрывающееся вещество громамонтов используются для приготовления
        зелий. Они и отнесены в Класс Б: «Товары, разрешённые к продаже» (но опасные и требующие строгого контроля).</p>
        <p><b>Нунду (англ. Nundu)</b> — это восточно-африканское животное является, возможно, самым опасным:
        гигантский леопард,
        передвигающийся, несмотря на свои размеры, бесшумно. Его дыхание вызывает болезни, способные опустошить целые
        деревни. Нунду ещё ни разу не покорился совместным усилиям менее чем сотни квалифицированных колдунов.</p>
        <p><b>Ревун, Фвупер (англ. Fwooper)</b> — это африканская птица с исключительно ярким оперением; встречаются
        ревуны
        оранжевой, розовой, ярко-зелёной или жёлтой расцветок. Перья ревунов издавна пользуются спросом в мире моды.
        Также ревуны известны тем, что откладывают яйца с очень красивым рисунком. Хотя поначалу песня ревуна может даже
        понравиться, она постепенно сводит слушателя с ума. Ревуны продаются только с наложенным на них Заглушающим
        заклинанием, которое необходимо ежемесячно обновлять. Право обладания ревуном предоставляется только при наличии
        разрешения, так как эти существа требуют ответственного отношения.</p>
        <p><b>Яркополз (англ. Streeler)</b> — это гигантская улитка, которая меняет цвет каждый час и оставляет за
        собой
        настолько ядовитый след, что он разъедает и выжигает всю растительность, по которой яркополз проползает. Родина
        яркополза — некоторые африканские страны, хотя он был успешно выращен волшебниками в Европе, Азии и Америке. Те,
        кому нравятся его калейдоскопические перемены цвета, содержат яркополза как домашнее животное; его яд — одно из
        немногих известных веществ, которое убивает хорклампа.</p>
        <p><b>Конгамато</b> – ящероподобное существо с крыльями летучей мыши размахом 1-2 м, напоминающий
        птеродактиля. Обитает
        в юго-центральной части Африки, можно защититься при помощи магии.</p>
        <p><b>Эмела-Нтука</b> – рептилия с копытами; у эмела-нтука очень скверный характер и единственный рог, который
        позволяет
        ему убивать слонов и других крупных животных одним ударом. Размером эмела-нтука со слона, а также у нее складки
        вокруг шеи, похожие на крокодила. Травоядные, но убивают всех встречающихся им на пути животных.</p>
        <p><b>Попобава</b> – карлик с одним глазом посреди лба, маленькими острыми ушами, крыльями и когтями летучей
        мыши.
        Опасное существо, встречается крайне редко.</p>

    </div>

    <div class="page-title" align="center">
        <h3>Высшие учебные заведения Африки</h3>
    </div>
    <div class="main-page-text">
        <p><b>Академия Анимагии Южно-Африканской Республики (Кейптаун, ЮАР)</b> – все зарегистрированные анимаги обязаны
            пройти
            там хотя бы обязательный шестимесячный курс, при желании можно пройти годовой курс. Незарегистрированным
            анимагам предлагается узаконить свои умения и пройти обучение в академии; отказавшиеся же или использующие
            свои
            способности в незаконных целях подлежат тюремному заключению в Герезани.</p>
        <p><b>Курсы при ОММА (подготовка мракоборцев, политиков и офисных работников)</b></p>

    </div>
{% endblock %}

templates/foundation/plot.html
{% extends 'base.html' %}

{% block content %}

    <div class="page-title" align="center">
        <h3>Сюжет</h3>
    </div>

    <div class="main-page-text">
        Хувеане – первый мчави на Земле, сотворивший землю, небеса и людей и подаривший им умение колдовать. Вскоре
        собственные дети надоели Хувеане, и он, разозлившись, забрал у них магию, превратив в симчави и, построив
        лестницу до небес, скрылся, убирая за собой каждую ступеньку, чтобы люди не смогли взобраться вслед за ним.
        Нескольким из них удалось скрыться от гнева создателя далеко в горах, сейчас называемых Лунными. С помощью своих
        чар племя спасшихся мчави сделали эти земли закрытыми для простых симчави и скрывались там от них долгие годы.
        Вскоре мчави поняли, что их создатель Хувеане не планирует возвращаться на землю, и, перестав бояться того, что
        он лишит их магии, разбрелись по всей земле, медленно смешиваясь с симчави, вступая с ними в брак и
        распространяя волшебство по всей планете. Мчави боялись, что если простые люди узнают об их способностях, они
        снова выгонят их в изгнание или даже убьют, и поэтому скрывали свои чары, притворяясь, что они такие же, как и
        все. Со временем многие из них уже не имели практически ничего общего со своими предками, кроме одного – дара, с
        таким трудом сбережённого от Хувеане.
        Но были и те, кто не бежал – они остались там, в Лунных Горах, построив себе огромный дворец, названный Уагаду,
        где обучали новые поколения молодых мчави со всего континента. Пять семей, никогда не покидающих Африку и не
        вступали в брак с нусумчави, мпьямчави и симчави, из поколения в поколение преподавали в этой школе – Мадаки,
        Ивеала, Акинтола, Бухари и Джабар. Директором школы мог стать только один из представителей этой династии, и
        хотя бы один из представителей династии был куратором факультета. Все пять семей считали своим главным
        предназначением передавать знания предков следующим поколениям, и поэтому практически все их представители
        связывали свою жизнь с преподавательством.
    </div>
{% endblock %}

templates/foundation/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="page-title" align="center">
        {% if siteuser.id == request.user.id %}
            <h3>Мой профиль</h3>
        {% else %}
            <h3>Профиль {{ siteuser.username }}</h3>
        {% endif %}
    </div>

    <div class="profile">
        <div class="about-user" alin="center">
            <p>
            <div class="author">{{ siteuser.username }}</div>
            </p>
            {% if siteuser.status %}
                <p>
                <div class="status">{{ siteuser.status }}</div></p>
            {% else %}
                <p>
                <div class="status">Нет статуса</div></p>
            {% endif %}
            {% if siteuser.photo %}
                <p><img src="{{ siteuser.photo.url }}" width="180" height="180" class="avatar" align="center"></p>
            {% else %}
                <p><img src="{% static 'images/you.jpg' %}" width="180" height="180" class="avatar" align="center"></p>
            {% endif %}
            {% if siteuser != request.user %}
                {% if is_sub %}
                    <form method="post"
                          action="{% url 'Friends:unsubscribe' pk=siteuser.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Отписаться"/>
                    </form>
                {% else %}
                    <form method="post"
                          action="{% url 'Friends:subscribe' pk=siteuser.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Подписаться"/>
                    </form>
                {% endif %}
            {% endif %}
        </div>
        <div class="posts-user">
            <p>
            <div class="posts-counter">Написано постов: {{ posts_counter }}</div>
            </p>
            {% if siteuser.email %}
                <p>
                <div class="posts-counter">Электронная почта: {{ siteuser.email }}</div>
                </p>
            {% else %}
                <p>
                <div class="posts-counter">Электронная почта: не указана</div>
                </p>
            {% endif %}
            {% if siteuser.id == request.user.id %}
                <p><a href="{% url 'profile_edit' pk=siteuser.id %}">Редактировать профиль</a></p>
            {% else %}
                <p>___________________________________________________________</p>
                <p>ㅤㅤㅤㅤㅤㅤㅤㅤ</p>
            {% endif %}

        </div>
    </div>
{% endblock %}

templates/foundation/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block content %}
    {% if object == request.user %}
        <div class="page-title" align="center">
            <h3>Редактировать профиль</h3>
        </div>
        <form class="menu" align="center" method="post" enctype="multipart/form-data">
            <div class="form-group">
                {% csrf_token %}
                {{ form|as_bootstrap }}
            </div>
            <div class="form-group">
                <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Отредактировать"/>
            </div>
        </form>
    {% else %}
        <div class="page-title" align="center">
            <h3>Кит моннан, хакер (:</h3>
        </div>
    {% endif %}
{% endblock %}

templates/foundation/rules.html
{% extends 'base.html' %}

{% block content %}
    <div class="page-title" align="center">
        <h3>Правила</h3>
    </div>

    <div class="main-page-text">
        <p>1. Тут я напишу правила</p>
        <p>2. Но я их ещё не придумала</p>
        <p>3. Потом добавлю</p>
        <p>4. Но это не точно</p>
    </div>
{% endblock %}

templates/foundation/search_result.html
{% extends 'base.html' %}

{% block content %}

    <div class="page-title" align="center">
        <h3>Результаты поиска</h3>
    </div>
    {% if object_list %}
        {% for u in object_list %}
            <div class="main-page-text">
                <p>логин: {{ u.username }}</p>
                <p>email: {{ u.email }}</p>
                <a href="{% url 'profile' pk=u.id %}">профиль</a>
                <p>___</p>
            </div>
        {% endfor %}
    {% endif %}

{% endblock %}