characters/urls.py
from django.urls import path

from characters.views import CharacterListView, MyCharacterListView, add_character, CreateCharacterView, \
    SubjectsListView, give_up_character, CharacterDeleteView

urlpatterns = [
    path('characters/', CharacterListView.as_view(), name='characters'),
    path('my_characters/', MyCharacterListView.as_view(), name='my_characters'),
    path('take_character/<int:character_id>', add_character, name='take'),
    path('give_up_character/<int:character_id>', give_up_character, name='give_up'),
    path('new_character/', CreateCharacterView.as_view(), name='new'),
    path('school/', SubjectsListView.as_view(), name='school'),
    path('delete/<int:pk>', CharacterDeleteView.as_view(), name='delete'),
]

chat/urls.py
from django.urls import path

from chat.views import NewMessageView, MyMessagesListView

urlpatterns = [
    path('new/', NewMessageView.as_view(), name='new'),
    path('messages/', MyMessagesListView.as_view(), name='messages')
]

role_game_forum/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path

from role_game_forum import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    url('', include('foundation.urls')),
    re_path(r'^characters/', include(('characters.urls', 'characters'), namespace='Characters')),
    re_path(r'^forum/', include(('forum.urls', 'forum'), namespace='Forum')),
    re_path(r'^friends/', include(('friends.urls', 'friends'), namespace='Friends')),
    re_path(r'^chat/', include(('chat.urls', 'chat'), namespace='Chat')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

characters/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from foundation.models import SiteUser


class Faculty(models.Model):
    name = models.CharField(max_length=10)
    description = models.TextField(blank=True)
    animal = models.ImageField(upload_to='photos')

    def __str__(self):
        return self.name


class Character(models.Model):
    is_canon = models.BooleanField()
    name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    age = models.IntegerField()
    BLOOD_STATUS_CHOICES = [
        ('p', 'чистокровный(ая)'),
        ('h', 'полукровка'),
        ('m', 'магглорождённый(ая)')
    ]
    blood_status = models.CharField(max_length=1, choices=BLOOD_STATUS_CHOICES)
    description = models.TextField()
    player = models.ForeignKey(SiteUser, on_delete=models.CASCADE, blank=True, default=None, null=True)
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE, blank=True, default=None, null=True)
    year = models.IntegerField(validators=[MinValueValidator(0),
                                           MaxValueValidator(12)], blank=True, default=0)
    photo = models.ImageField(upload_to='photos')

    def __str__(self):
        return self.name + " " + self.last_name


class Subject(models.Model):
    name = models.CharField(max_length=30)
    teacher = models.ForeignKey(Character, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name

characters/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from characters.models import Character, Subject, Faculty


class CharacterListView(ListView):
    model = Character
    template_name = 'characters/characters.html'


class MyCharacterListView(LoginRequiredMixin, ListView):
    model = Character
    template_name = 'characters/my_characters.html'

    def get_queryset(self):
        return Character.objects.filter(player=self.request.user)


@login_required
def add_character(request, character_id):
    character = Character.objects.get(id=character_id)
    character.player = request.user
    character.save()
    return redirect('Characters:characters')


@login_required()
def give_up_character(request, character_id):
    character = Character.objects.get(id=character_id)
    character.player = None
    character.save()
    return redirect('Characters:characters')


class CreateCharacterView(LoginRequiredMixin, CreateView):
    model = Character
    template_name = 'characters/new_character.html'
    fields = ['name', 'last_name', 'age', 'blood_status', 'description', 'faculty', 'year', 'photo']
    success_url = reverse_lazy('Characters:my_characters')

    def form_valid(self, form):
        form.instance.player = self.request.user
        form.instance.is_canon = False
        return super(CreateCharacterView, self).form_valid(form)


class CharacterDeleteView(LoginRequiredMixin, DeleteView):
    model = Character
    success_url = reverse_lazy('Characters:characters')


class SubjectsListView(ListView):
    template_name = 'foundation/about_school.html'
    model = Subject
    context_object_name = 'subjects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['faculties'] = Faculty.objects.all()
        return context

templates/characters/character_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="main-page-text">
            <p>Вы уверены что хотите удалить персонажа "{{ object.name }} {{ object.last_name }}"?</p>
        </div>
        <div class="main-page-text">
            <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Да">
            <a href="{% url 'Characters:characters' %}" class="btn btn-outline-success my-2 my-sm-0">Нет</a>
        </div>
    </form>
{% endblock %}

templates/characters/characters.html
{% extends 'base.html' %}

{% block content %}


    {% if character_list %}
        <div class="page-title" align="center">
            <h3>Каноны ролевой</h3>
        </div>
        {% for c in character_list %}
            {% if c.is_canon %}
                <div class="profile">
                    <div class="about-user" align="center">
                        <div class="author">{{ c.name }} {{ c.last_name }}</div>
                        <p></p>
                        {% if c.player %}
                            {% if c.player != request.user %}
                                <div class="status">игрок: {{ c.player.username }}</div>
                            {% elif c.player == request.user %}
                                <a href="{% url 'Characters:give_up' character_id=c.id %}">Отказаться от персонажа</a>
                            {% endif %}
                        {% else %}
                            <div class="status"><a href="#" class="nav-link dropdown-toggle" href="#"
                                                   data-toggle="modal"
                                                   data-target="#{{ c.name }}{{ c.last_name }}{{ c.age }}"
                                                   onclick="return false"
                                                   role="button">занять</a>
                            </div>
                        {% endif %}
                        <p></p>
                        <p><img src="{{ c.photo.url }}" width="180" height="180" class="avatar" align="center"></p>
                    </div>
                    <div class="posts-user">
                        {% if c.faculty %}
                            <div class="posts-counter"><b>факультет: </b>{{ c.faculty.name }}</div>
                        {% else %}
                            <div class="posts-counter"><b>преподаватель</b></div>
                        {% endif %}
                        {% if c.blood_status == 'p' %}
                            <div class="posts-counter"><b>статус крови:</b> чистокровный(ая)</div>
                        {% elif c.blood_status == 'h' %}
                            <div class="posts-counter"><b>статус крови:</b> полукровка</div>
                        {% elif c.blood_status == 'm' %}
                            <div class="posts-counter"><b>статус крови:</b> магглорождённый(ая)</div>
                        {% endif %}
                        <div class="posts-counter"><b>возраст:</b> {{ c.age }}</div>
                        {% if c.year != 0 %}
                            <div class="posts-counter"><b>курс:</b> {{ c.year }}</div>
                        {% endif %}
                        <p></p>
                        <div class="posts-counter"><b> <a href="#" data-toggle="modal"
                                                          data-target="#{{ c.name }}{{ c.last_name }}"
                                                          onclick="return false"
                                                          role="button">Описание
                            персонажа</a></b></div>
                    </div>
                </div>
                <div class="modal fade" id="{{ c.name }}{{ c.last_name }}" tabindex="-1" role="dialog"
                     aria-labelledby="description"
                     aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalScrollableTitle">Описание персонажа</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                {{ c.description }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="{{ c.name }}{{ c.last_name }}{{ c.age }}" tabindex="-1" role="dialog"
                     aria-labelledby="pick" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalScrollableTitle">Подтверждение действия</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Вы хотите занять этого персонажа?
                            </div>
                            <div class="modal-footer">
                                <form action="{% url 'Characters:take' character_id=c.pk %}" method="post">
                                    {% csrf_token %}
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
                                    <button type="submit" class="btn btn-primary">Да</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        <p></p>
        ㅤㅤㅤㅤㅤㅤ


        <div class="page-title" align="center">
            <h3>Неканоны ролевой</h3>
        </div>
        {% for c in character_list %}
            {% if c.is_canon == False %}
                <div class="profile">
                    <div class="about-user" align="center">
                        <p>
                        <div class="author">{{ c.name }} {{ c.last_name }}</div>
                        </p>
                        <p>
                            {% if c.player != request.user %}
                                <div class="status">игрок: {{ c.player.username }}</div>
                            {% else %}
                                <a href="{% url 'Characters:delete' pk=c.pk %}">Удалить персонажа</a>
                            {% endif %}
                        </p>
                        <p><img src="{{ c.photo.url }}" width="180" height="180" class="avatar" align="center"></p>
                    </div>
                    <div class="posts-user">
                        {% if c.faculty %}
                            <div class="posts-counter"><b>факультет: </b>{{ c.faculty.name }}</div>
                        {% else %}
                            <div class="posts-counter"><b>преподаватель</b></div>
                        {% endif %}
                        {% if c.blood_status == 'p' %}
                            <div class="posts-counter"><b>статус крови:</b> чистокровный(ая)</div>
                        {% elif c.blood_status == 'h' %}
                            <div class="posts-counter"><b>статус крови:</b> полукровка</div>
                        {% elif c.blood_status == 'm' %}
                            <div class="posts-counter"><b>статус крови:</b> магглорождённый(ая)</div>
                        {% endif %}
                        <div class="posts-counter"><b>возраст:</b> {{ c.age }}</div>
                        {% if c.year != 0 %}
                            <div class="posts-counter"><b>курс:</b> {{ c.year }}</div>
                        {% endif %}
                        <p></p>
                        <div class="posts-counter"><b> <a href="#" data-toggle="modal"
                                                          data-target="#{{ c.name }}{{ c.last_name }}"
                                                          onclick="return false"
                                                          role="button">Описание
                            персонажа</a></b></div>
                    </div>
                </div>

                <div class="modal fade" id="{{ c.name }}{{ c.last_name }}" tabindex="-1" role="dialog"
                     aria-labelledby="description"
                     aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalScrollableTitle">Описание персонажа</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                {{ c.description }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% else %}
        Пока не создано ни одного персонажа.
    {% endif %}


    <!-- Modal -->
    <div class="modal fade" id="pick" tabindex="-1" role="dialog" aria-labelledby="pick" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalScrollableTitle">Подтверждение действия</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Вы хотите занять этого персонажа?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
                    <button type="button" class="btn btn-primary">Да</button>
                </div>
            </div>
        </div>
    </div>





{% endblock %}

templates/characters/my_characters.html
{% extends 'base.html' %}

{% block content %}

    <div class="page-title" align="center">
        <h3>Мои персонажи</h3>
    </div>
    {% if character_list %}
        {% for c in character_list %}
                <div class="profile">
                    <div class="about-user" align="center">
                        <div class="author">{{ c.name }} {{ c.last_name }}</div>
                        <p></p>
                        <div class="status">игрок: {{ c.player.username }}</div>
                        <p></p>
                        <p><img src="{{ c.photo.url }}" width="180" height="180" class="avatar" align="center"></p>
                    </div>
                    <div class="posts-user">
                        {% if c.faculty %}
                            <div class="posts-counter"><b>факультет: </b>{{ c.faculty.name }}</div>
                        {% else %}
                            <div class="posts-counter"><b>преподаватель</b></div>
                        {% endif %}
                        {% if c.blood_status == 'p' %}
                            <div class="posts-counter"><b>статус крови:</b> чистая кровь</div>
                        {% elif c.blood_status == 'h' %}
                            <div class="posts-counter"><b>статус крови:</b> полукровка</div>
                        {% elif c.blood_status == 'm' %}
                            <div class="posts-counter"><b>статус крови:</b> магглорождённый(ая)</div>
                        {% endif %}
                        <div class="posts-counter"><b>возраст:</b> {{ c.age }}</div>
                        {% if c.year != 0 %}
                            <div class="posts-counter"><b>курс:</b> {{ c.year }}</div>
                        {% endif %}
                        <p></p>
                        <div class="posts-counter"><b> <a href="#" data-toggle="modal"
                                                          data-target="#{{ c.name }}{{ c.last_name }}"
                                                          onclick="return false"
                                                          role="button">Описание
                            персонажа</a></b></div>
                    </div>
                </div>
                <div class="modal fade" id="{{ c.name }}{{ c.last_name }}" tabindex="-1" role="dialog"
                     aria-labelledby="description"
                     aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalScrollableTitle">Описание персонажа</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                {{ c.description }}
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
    {% else %}
        Персонажей пока нет.
    {% endif %}
{% endblock %}

templates/characters/new_character.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block content %}
    <div class="page-title" align="center">
        <h3>Создание персонажа</h3>
    </div>
    <form class="menu" method="post" action="{% url 'Characters:new' %}" enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}
        {{ form|as_bootstrap }}
    </div>
    <div class="form-group">
        <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Создать" align="center"/>
    </div>
    </form>
{% endblock %}