chat/urls.py
from django.urls import path

from chat.views import NewMessageView, MyMessagesListView

urlpatterns = [
    path('new/', NewMessageView.as_view(), name='new'),
    path('messages/', MyMessagesListView.as_view(), name='messages')
]

forum/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView
from rest_framework_swagger.views import get_swagger_view

from forum.views import ForumListView, ForumPageView, AllSectionsView, SystemPostFormView, like, dislike, \
    GamePostFormView, PostDeleteView, SingleSectionView

schema_view = get_swagger_view(title='Sections API Documentation')

urlpatterns = [
    # app urls
    path('list/', ForumListView.as_view(), name='list'),
    path('page/<int:pk>', ForumPageView.as_view(), name='page'),
    path('new/system/', SystemPostFormView.as_view(), name='new_system'),
    path('like/<int:pk>', like, name='like'),
    path('dislike/<int:pk>', dislike, name='dislike'),
    path('new/game/', GamePostFormView.as_view(), name='new_game'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='delete'),

    # api urls
    path('api/sections/', AllSectionsView.as_view(), name='api_sections'),
    path('api/sections/<int:pk>/', SingleSectionView.as_view(), name='api_section'),
    url(r'^documentation/', schema_view, name='doc'),
]

role_game_forum/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path

from role_game_forum import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    url('', include('foundation.urls')),
    re_path(r'^characters/', include(('characters.urls', 'characters'), namespace='Characters')),
    re_path(r'^forum/', include(('forum.urls', 'forum'), namespace='Forum')),
    re_path(r'^friends/', include(('friends.urls', 'friends'), namespace='Friends')),
    re_path(r'^chat/', include(('chat.urls', 'chat'), namespace='Chat')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

forum/models.py
from typing import Any

from django.db import models
from django.db.models import Model
from rest_framework import serializers

from characters.models import Character
from foundation.models import SiteUser


# for game themes only
class Section(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class SectionSerializer(serializers.ModelSerializer):
    class Meta:
        model = Section
        fields = ['id', 'name', 'description']

    def create(self, validated_data):
        return Section.objects.create(**validated_data)

    def update(self, instance: Model, validated_data: Any):
        instance.name = validated_data.get('name', instance.name)
        instance.description = validated_data.get('description', instance.description)
        instance.save()
        return instance


class Theme(models.Model):
    name = models.CharField(max_length=50)
    section = models.ForeignKey(Section, on_delete=models.CASCADE, blank=True, null=True)
    first_post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='first_post')
    is_open = models.BooleanField()
    is_game = models.BooleanField()

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(SiteUser, on_delete=models.CASCADE)
    text = models.TextField()
    character = models.ForeignKey(Character, on_delete=models.CASCADE, blank=True, null=True)
    picture = models.ImageField(upload_to='photos', blank=True, null=True)
    when = models.DateTimeField()
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE, related_name='theme', blank=True, null=True)
    url = models.URLField(blank=True, null=True, default=None)

    def __str__(self):
        return self.author.username + '^' + self.text


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('post', 'user'),)

    def __str__(self):
        return self.post.text + ': ' + self.user.username


class Dislike(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(SiteUser, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('post', 'user'),)

    def __str__(self):
        return self.post.text + ': ' + self.user.username

forum/forms.py
from django.forms import ModelForm

from characters.models import Character
from forum.models import Post, Theme


class GamePostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['character', 'text', 'picture', 'theme']

    def __init__(self, user, *args, **kwargs):
        super(GamePostForm, self).__init__(*args, **kwargs)
        self.fields['character'].queryset = Character.objects.filter(player=user)
        self.fields['theme'].queryset = Theme.objects.filter(is_game=True, is_open=True)


class SystemPostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'picture', 'theme']

    def __init__(self, *args, **kwargs):
        super(SystemPostForm, self).__init__(*args, **kwargs)
        self.fields['theme'].queryset = Theme.objects.filter(is_game=False, is_open=True)

forum/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import register
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import TemplateView, DetailView, FormView, DeleteView
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.response import Response

from forum.forms import SystemPostForm, GamePostForm
from forum.models import Theme, Section, Post, SectionSerializer, Like, Dislike
from rest_framework.views import APIView


class ForumListView(TemplateView):
    template_name = 'forum/forum_list.html'

    def get_context_data(self, **kwargs):
        context = super(ForumListView, self).get_context_data(**kwargs)
        context['themes'] = Theme.objects.filter(is_game=False)
        context['game_themes'] = Theme.objects.filter(is_game=True)
        context['sections'] = Section.objects.all()
        return context


class ForumPageView(DetailView):
    model = Theme
    template_name = 'forum/forum_page.html'
    context_object_name = 'theme'

    def get_context_data(self, **kwargs):
        context = super(ForumPageView, self).get_context_data(**kwargs)
        posts = Post.objects.filter(theme=self.object).order_by('when')
        context['posts'] = posts
        context['first_likes'] = Like.objects.filter(post=self.object.first_post).count()
        context['first_dislikes'] = Dislike.objects.filter(post=self.object.first_post).count()
        likes = {}
        dislikes = {}
        for p in posts:
            likes[p.pk] = Like.objects.filter(post=p).count()
            dislikes[p.pk] = Dislike.objects.filter(post=p).count()
        context['likes'] = likes
        context['dislikes'] = dislikes
        return context


class SystemPostFormView(LoginRequiredMixin, FormView):
    form_class = SystemPostForm
    template_name = 'forum/new_system_post.html'

    def get_success_url(self):
        return reverse_lazy(self.request.POST.get('next', 'Forum:list'))

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.when = timezone.now()
        form.save()
        return super(SystemPostFormView, self).form_valid(form)


class GamePostFormView(LoginRequiredMixin, FormView):
    form_class = GamePostForm
    template_name = 'forum/new_game_post.html'

    def get_form_kwargs(self):
        kwargs = super(GamePostFormView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse_lazy('Forum:list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.when = timezone.now()
        form.save()
        return super(GamePostFormView, self).form_valid(form)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('Forum:list')


@login_required
def like(request, pk):
    if Like.objects.filter(post_id=pk, user=request.user).exists():
        Like.objects.get(post_id=pk, user=request.user).delete()
    else:
        if Dislike.objects.filter(post_id=pk, user=request.user).exists():
            Dislike.objects.get(post_id=pk, user=request.user).delete()
        Like.objects.create(post_id=pk, user=request.user)
    next_page = request.POST.get('next', 'main_page')
    return HttpResponseRedirect(next_page)


@login_required()
def dislike(request, pk):
    if Dislike.objects.filter(post_id=pk, user=request.user).exists():
        Dislike.objects.get(post_id=pk, user=request.user).delete()
    else:
        if Like.objects.filter(post_id=pk, user=request.user).exists():
            Like.objects.get(post_id=pk, user=request.user).delete()
        Dislike.objects.create(post_id=pk, user=request.user)
    next_page = request.POST.get('next', 'main_page')
    return HttpResponseRedirect(next_page)


# filter for getting an item from dictionary by it's key in templates
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


# old version of api for Section objects
# class AllSectionView(APIView):
#
#     def get(self):
#         sections = SectionSerializer(Section.objects.all(), many=True)
#         return Response({'sections': sections.data})
#
#     def post(self, request):
#         section = request.data.get('section')
#         serializer = SectionSerializer(data=section)
#         if serializer.is_valid(raise_exception=True):
#             section_saved = serializer.save()
#         return Response({"success": "Section '{}' created successfully".format(section_saved.name)})
#
#     def put(self, request, pk):
#         saved_section = get_object_or_404(Section.objects.all(), pk=pk)
#         data = request.data.get('article')
#         serializer = SectionSerializer(instance=saved_section, data=data, partial=True)
#         if serializer.is_valid(raise_exception=True):
#             section_saved = serializer.save()
#         return Response({
#             "success": "Section '{}' updated successfully".format(section_saved.name)
#         })
#
#     def delete(self, pk):
#         section = get_object_or_404(Section.objects.all(), pk=pk)
#         section.delete()
#         return Response({
#             "message": "Section with id `{}` has been deleted.".format(pk)
#         }, status=204)


class AllSectionsView(ListCreateAPIView):
    queryset = Section.objects.all()
    serializer_class = SectionSerializer

    def perform_create(self, serializer):
        return serializer.save()


class SingleSectionView(RetrieveUpdateDestroyAPIView):
    queryset = Section.objects.all()
    serializer_class = SectionSerializer

templates/forum/forum_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="page-title" align="center">
        <h3>Обсуждения</h3>
    </div>

    <div class="location-topic" align="center"><b>Организационные темы:</b></div>
    {% if themes %}
        {% for t in themes %}
            <div class="location-list">
                <div class="location-link">
                    <a href="{% url 'Forum:page' pk=t.pk %}">{{ t.name }}</a>
                    <p>Создано: {{ t.first_post.when }}</p>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="main-page-text">Пока не создано ни одной темы.</div>
    {% endif %}

    <div class="location-topic" align="center"><b>Игровые темы:</b></div>
    {% if game_themes %}
        {% for s in sections %}
            <div class="location-topic" align="center">{{ s.name }}</div>
            {% for t in game_themes %}
                {% if t.section == s %}
                    <div class="location-list">
                        <div class="location-link">
                            <a href="{% url 'Forum:page' pk=t.pk %}">{{ t.name }}</a>
                            <p>{{ t.first_post.when }}</p>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endfor %}
    {% else %}
        <div class="main-page-text">Пока не создано ни одной темы.</div>
    {% endif %}


{% endblock %}

templates/forum/forum_page.html
{% extends 'base.html' %}
{% load bootstrap_tags %}


{% block content %}
    <div class="page-title" align="center">
        <h3>{{ theme.name }}</h3>
    </div>

    <div class="post-box">
        <div class="post-time">
            {{ theme.first_post.when }}
        </div>
        <div class="post-author">
            <ul>
                <p>
                <div class="author"><a
                        href="{% url 'profile' pk=theme.first_post.author.pk %}">{{ theme.first_post.author.username }}</a>
                </div>
                </p>
                <p>
                <div class="status">{{ theme.first_post.author.status }}</div>
                </p>
                {% if theme.first_post.author.photo %}
                    <p><img src="{{ theme.first_post.author.photo.url }}" width="180" height="180" class="avatar"
                            align="center"></p>
                {% endif %}
                <!--<p><div class="posts-counter">Сообщений: 249</div></p>-->
            </ul>
        </div>
        <div class="post-body">
            <div id="p193244-content" class="post-content">
                {{ theme.first_post.text }}
                <p>___________________________________________________________________</p>
                {% if theme.first_post.picture %}
                    <img src="{{ theme.first_post.picture.url }}" class="avatar">
                    <p>___________________________________________________________________</p>
                {% endif %}
                <form method="post"
                      action="{% url 'Forum:like' pk=theme.first_post.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Мне нравится"/>
                </form>
                <p></p>
                <form method="post"
                      action="{% url 'Forum:dislike' pk=theme.first_post.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Мне не нравится"/>
                </form>
                <p>___________________________________________________________________</p>
                <p><b>Лайки:</b> {{ first_likes }} <b>Дизлайки:</b> {{ first_dislikes }}</p>
            </div>
        </div>
    </div>

    {% for post in posts %}
        <div class="post-box">
            <div class="post-time">
                {{ post.when }}
            </div>
            <div class="post-author">
                <ul>
                    <p>
                    <div class="author"><a
                            href="{% url 'profile' pk=post.author.pk %}">{{ post.author.username }}</a>
                    </div>
                    </p>
                    <p>
                    <div class="status">{{ post.author.status }}</div>
                    </p>
                    {% if post.author.photo %}
                        <p><img src="{{ post.author.photo.url }}" width="180" height="180" class="avatar"
                                align="center"></p>
                    {% endif %}
                    <!--<p><div class="posts-counter">Сообщений: 249</div></p>-->
                </ul>
            </div>
            <div class="post-body">
                <div id="p193244-content" class="post-content">
                    {% if post.character %}
                        <p><b>персонаж:</b> <i>{{ post.character.name }} {{ post.character.last_name }}</i></p>
                    {% endif %}
                    {{ post.text }}
                    {% if post.url %}
                        <p><b>ссылка:</b> <i><a href="{{ post.url }}">{{ post.url }}</a> </i></p>
                    {% endif %}
                    <p>___________________________________________________________________</p>
                    {% if post.picture %}
                        <div>
                            <img src="{{ post.picture.url }}" class="avatar">
                        </div>
                        <p>___________________________________________________________________</p>
                    {% endif %}

                    <form method="post"
                          action="{% url 'Forum:like' pk=post.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Мне нравится"/>
                    </form>
                    <p></p>
                    <form method="post"
                          action="{% url 'Forum:dislike' pk=post.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Мне не нравится"/>
                    </form>
                    <p>___________________________________________________________________</p>
                    <p><b>Лайки:</b> {{ likes|get_item:post.id }} <b>Дизлайки:</b> {{ dislikes|get_item:post.id }}</p>
                    {% if post.author == request.user %}
                        <a href="{% url 'Forum:delete' pk=post.id %}">Удалить пост</a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
    {% if request.user.is_authenticated == False %}
        <div class="main-page-text">Чтобы написать пост в этой теме, <a href="{% url 'login' %}">войдите</a>.</div>
    {% elif theme.is_open == False %}
        <div class="main-page-text">Данная тема закрыта.</div>
    {% elif theme.is_game %}
        <form method="get" action="{% url 'Forum:new_game' %}" class="main-page-text">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}">
            <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Новый пост"/>
        </form>
    {% elif theme.is_game == False %}
        <form method="get" action="{% url 'Forum:new_system' %}" class="main-page-text">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}">
            <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Новый пост"/>
        </form>
    {% endif %}
{% endblock %}

templates/forum/new_game_post.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block content %}
    <div class="page-title" align="center">
        <h3>Новый игровой пост</h3>
    </div>
    <form class="menu" method="post" action="{% url 'Forum:new_game' %}" enctype="multipart/form-data">
        <div class="form-group">
            {% csrf_token %}
            {{ form|as_bootstrap }}
        </div>
        <div class="form-group">
            <input type="hidden" value="{{ request.theme_id }}" name="theme_id"/>
            <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Создать" align="center"/>
        </div>
    </form>
{% endblock %}

templates/forum/new_system_post.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block content %}
    <div class="page-title" align="center">
        <h3>Новый системный пост</h3>
    </div>
    <form class="menu" method="post" action="{% url 'Forum:new_system' %}" enctype="multipart/form-data">
        <div class="form-group">
            {% csrf_token %}
            {{ form|as_bootstrap }}
        </div>
        <div class="form-group">
            <input type="hidden" value="{{ request.theme_id }}" name="theme_id"/>
            <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Создать" align="center"/>
        </div>
    </form>
{% endblock %}

templates/forum/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="main-page-text">
            <p>Вы уверены что хотите удалить пост "{{ object.text }}"?</p>
        </div>
        <div class="main-page-text">
            <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Да">
            <a href="{% url 'Forum:page' pk=object.theme.id %}" class="btn btn-outline-success my-2 my-sm-0">Нет</a>
        </div>
    </form>
{% endblock %}